// Generated by gencpp from file augmented_whycon/AugmentedWhyConMsg.msg
// DO NOT EDIT!


#ifndef AUGMENTED_WHYCON_MESSAGE_AUGMENTEDWHYCONMSG_H
#define AUGMENTED_WHYCON_MESSAGE_AUGMENTEDWHYCONMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Quaternion.h>

namespace augmented_whycon
{
template <class ContainerAllocator>
struct AugmentedWhyConMsg_
{
  typedef AugmentedWhyConMsg_<ContainerAllocator> Type;

  AugmentedWhyConMsg_()
    : header()
    , poses()
    , nrDetectedLShapes()
    , idx()
    , LShapesIdxs()
    , LShapesOri()  {
    }
  AugmentedWhyConMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)
    , nrDetectedLShapes(_alloc)
    , idx(_alloc)
    , LShapesIdxs(_alloc)
    , LShapesOri(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _nrDetectedLShapes_type;
  _nrDetectedLShapes_type nrDetectedLShapes;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _idx_type;
  _idx_type idx;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _LShapesIdxs_type;
  _LShapesIdxs_type LShapesIdxs;

   typedef std::vector< ::geometry_msgs::Quaternion_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Quaternion_<ContainerAllocator> >::other >  _LShapesOri_type;
  _LShapesOri_type LShapesOri;




  typedef boost::shared_ptr< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> const> ConstPtr;

}; // struct AugmentedWhyConMsg_

typedef ::augmented_whycon::AugmentedWhyConMsg_<std::allocator<void> > AugmentedWhyConMsg;

typedef boost::shared_ptr< ::augmented_whycon::AugmentedWhyConMsg > AugmentedWhyConMsgPtr;
typedef boost::shared_ptr< ::augmented_whycon::AugmentedWhyConMsg const> AugmentedWhyConMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace augmented_whycon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'augmented_whycon': ['/home/pfeiffer/catkin_ws/src/whyconLshape/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b77e673bc19c526df867e458fa38e03";
  }

  static const char* value(const ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b77e673bc19c526ULL;
  static const uint64_t static_value2 = 0xdf867e458fa38e03ULL;
};

template<class ContainerAllocator>
struct DataType< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "augmented_whycon/AugmentedWhyConMsg";
  }

  static const char* value(const ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Pose[] poses\n\
geometry_msgs/Vector3[] nrDetectedLShapes\n\
geometry_msgs/Vector3[] idx\n\
geometry_msgs/Vector3[] LShapesIdxs\n\
geometry_msgs/Quaternion[] LShapesOri\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
      stream.next(m.nrDetectedLShapes);
      stream.next(m.idx);
      stream.next(m.LShapesIdxs);
      stream.next(m.LShapesOri);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AugmentedWhyConMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::augmented_whycon::AugmentedWhyConMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "nrDetectedLShapes[]" << std::endl;
    for (size_t i = 0; i < v.nrDetectedLShapes.size(); ++i)
    {
      s << indent << "  nrDetectedLShapes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.nrDetectedLShapes[i]);
    }
    s << indent << "idx[]" << std::endl;
    for (size_t i = 0; i < v.idx.size(); ++i)
    {
      s << indent << "  idx[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.idx[i]);
    }
    s << indent << "LShapesIdxs[]" << std::endl;
    for (size_t i = 0; i < v.LShapesIdxs.size(); ++i)
    {
      s << indent << "  LShapesIdxs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.LShapesIdxs[i]);
    }
    s << indent << "LShapesOri[]" << std::endl;
    for (size_t i = 0; i < v.LShapesOri.size(); ++i)
    {
      s << indent << "  LShapesOri[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "    ", v.LShapesOri[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUGMENTED_WHYCON_MESSAGE_AUGMENTEDWHYCONMSG_H
