set(_CATKIN_CURRENT_PACKAGE "augmented_whycon")
set(augmented_whycon_VERSION "0.0.0")
set(augmented_whycon_MAINTAINER "Kevin Chappellet <kevin.chappellet@lirmm.fr>")
set(augmented_whycon_PACKAGE_FORMAT "1")
set(augmented_whycon_BUILD_DEPENDS "message_generation" "roscpp" "std_msgs" "geometry_msgs" "tf")
set(augmented_whycon_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "tf")
set(augmented_whycon_BUILDTOOL_DEPENDS "catkin")
set(augmented_whycon_BUILDTOOL_EXPORT_DEPENDS )
set(augmented_whycon_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "tf")
set(augmented_whycon_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "tf")
set(augmented_whycon_TEST_DEPENDS )
set(augmented_whycon_DOC_DEPENDS )
set(augmented_whycon_DEPRECATED "")